(function(g){function F(a){"$ignore"===a&&(e.define=w,w=null)}function G(a,b,c){c||(c=b,b=[]);k=0;z[a]=!0;p(b,function(){m[a]=c.apply(null,arguments)})}function p(){n.push(arguments);A()}function A(){var a,b,c,d,f,e,g,h;if(n.length){a=n;n=[];e={};l=[];for(b=a.length;b--;){d=[];g=!0;for(c=a[b][0].length;c--;)f=a[b][0][c],f in m?d[c]=m[f]:(e[f]||z[f]||(l.push(f),e[f]=!0),g&&(n.push(a[b]),g=!1));if(g){h=!0;try{a[b][1].apply(null,d)}catch(k){q(k,"runtime")}}}h?A():n.length&&!r&&(r=x(B,100))}}function B(){var a,
b,c,d,f=[];r=C(r);if(!k){y=C(y);for(a=l.length;a--;)d=l[a],t[d]?(l.splice(a,1),2>t[d]&&(t[d]++,f.push(d))):t[d]=1;k=l.length;f.length&&q(Error("Modules '"+f.join("', '")+"' failed to load"),"loadFailed");if(k){y=x(H,6E4);try{b=h.createElement("script"),b.src=I+"//s2.adform.net/stoat/620/s2.adform.net/load/v/0.0.189/e/"+m.$env.$hash()+"/i/"+m.$ignore+"/r:"+l.sort().join(":"),c=h.__gEBTN__("script")[0],b.onerror=J,c?c.parentNode.insertBefore(b,c):(h.body||h.head).appendChild(b)}catch(e){q(e,"script_insert")}}}}function J(){u("response_error",
this.src)}function H(){k=0;B()}function u(a,b,c,d){var f=[],e=g.Image;Math.random()<(c||.03)&&(f.push((v&&v.host||"//track.adform.net")+"/serving/jslog/"),f.push("?src="),f.push(encodeURIComponent(a)),f.push("&msg="),f.push(encodeURIComponent(b)),f.push("&level="),f.push(encodeURIComponent(d||"error")),a=e?new e(1,1):h.createElement("img"),a.src=f.join(""))}function q(a,b){var c=""+(a.stack||a);0>c.indexOf(a.message||"")&&(c=a+"\n"+c);x(function(){throw c;},0);u(b,c)}function D(){for(var a=arguments,
b=0,c=a.length,d=[];b<c;b++)K(a[b])||d.push(a[b]);return d.length?E.apply(e,d):e.length}function K(a){function b(b){b.apply(null,a.slice(1))}var c=a[0],d=m[c];d?b(d):p([c],b)}var w,E,r,y,l,e=g._adfq||(g._adfq=[]),h=g.document,x=g.setTimeout,C=g.clearTimeout,v=g.Adform,I=v&&"https:"===(v.shost||"").split("/")[0]||"https:"===g.location.protocol?"https:":"http:",m={require:p,$boot:{window:g,require:p,rethrow:q,log:u,deprecate:function(a,b,c){var d=!1;return function(){d||(u("deprecate",b,c,"info"),d=
!0);return a.apply(this,arguments)}}}},k=0,n=[],z={},t={};h.__gEBTN__=h.getElementsByTagName;(function(){var a;e.define?(w=e.define,e.define=F):(E=e.push,e.define=G,e.push=D,a=e.slice(),e.length=0,D.apply(e,a))})()})(window);
(function(a,j,c,b,g,Q,O,P,R,S,e,J,L,M,z,B,x,N,K,f){
a(j,[c],function(c){c=c.window;var a=c.Adform||{},d=a.ET||{},b=a.RMB||{},e=b.Content||{};b.Type=b.Type||{};b.Content=e;a.ET=d;a.RMB=b;return c.Adform=a});
a(b,[c],function(R){function E(f){return f}function F(){function f(){for(var a=1,d=m;a<g.length&&!g[a];a++)d=d.parent;try{return d==d.Function("return window")()}catch(b){}}function t(a,d){var b=d.charAt(0).toUpperCase()+d.slice(1);return h(a,d,"ms"+b,"moz"+b,"webkit"+b)}function h(a){for(var d=arguments,b=d.length;--b;)if(d[b]in a)return d[b]}function c(a,d){return 0<=(""+a).toLowerCase().indexOf(d.toLowerCase())}var a=R.window,e=a.document,y=e.documentElement,k=a.navigator,m=a.parent,n=
k.vendor,b=k.userAgent,z=a.location||{},A=e.createElement("div"),g=function(a){for(var d,b=100,c=a.top,e=[!0];--b&&a&&a!=c&&a!=a.parent;){try{d=!!(a=a.parent).Image}catch(f){d=!1}e.push(d)}return e}(a),u=a!=m,x=!u||g[1],p=!u||g[g.length-1],S=u&&f(),E=function(){var b,d=k.plugins,c=k.mimeTypes,e=a.ActiveXObject,f=26,d=d&&d["Shockwave Flash"]&&(!c||!c["application/x-shockwave-flash"]||c["application/x-shockwave-flash"].enabledPlugin)&&(d["Shockwave Flash"].version||d["Shockwave Flash"].description)||
"";if(!d&&e)for(;6<=f--;)try{b=new e("ShockwaveFlash.ShockwaveFlash."+f);6==f&&(b.AllowScriptAccess="always",d="WIN 6.0.21.0");try{d=b.GetVariable("$version").replace(/,/g,".")}catch(g){}break}catch(g){}return parseFloat(d.replace(/^.*?(\d+[\.,].*$)/,"$1").replace(/(^\d+\.)|\./g,"$1"))||0}(),T=t(e,"hidden"),G=!!T,B=/MSIE|Trident/i.test(b),U=B&&("Microsoft Internet Explorer"===k.appName&&/MSIE (\d+[\.\d]*)/i.exec(b)||/rv:(\d+[\.\d]*)/i.exec(b))?parseFloat(RegExp.$1):-1,A=h(A,"addEventListener"),V=
c(b,"Macintosh"),C=c(n,"apple computer"),H=c(b,"ipad"),I=c(b,"iphone"),q=H||I,r;r=q&&(r=/\sos\s(\d+)_\d+/i.exec(b))&&(r=4<r[1]>>0);var J=c(n,"google"),K=!q&&c(b,"android"),W="ontouchstart"in e||"ontouchstart"in a,L=(C||J)&&/(chrome|crios)+\/[\d\.]+\s/i.test(b),F=L&&/[chrome|crios]+\/([\d\.]+)\s/i.exec(b)[1],D=/Firefox\/[\d\.]+/i.test(b),X=c(b,"opera"),n=c(b,"opr")&&c(n,"opera software"),v=!/Chrome|CriOS|Skyfire/i.test(b)&&/Safari+\/[\.\d]+$/i.test(b)&&C,b=B&&(c(b,"IEMobile")||c(b,"WPDesktop")),Y=
v&&!("webkitRequestAnimationFrame"in a),Z="screenX"in a,aa="outerWidth"in a,ba="mozInnerScreenX"in a,y=y.msContentZoomFactor,ca=!(!e.fireEvent||!e.attachEvent),na=t(a,"requestAnimationFrame"),da=q&&!v&&!k.standalone,ea=h(a,"IntersectionObserver")&&!D,z=!!("srcdoc"in e.createElement("iframe"))&&c(z.href,"adform.com")&&!D,M=q||K,l=p?a.top.omid3p:a.omid3p;if(!l)try{l=a.frames.omid_v1_present||a.top.frames.omid_v1_present}catch(pa){}var l=!!l,e=G&&!l&&!M&&!b&&p&&h(e,"hasFocus"),fa=!p&&11==U,N,O,w=a.wisp,
ga=w&&w.sdk&&w.sdk.platform,ha=v&&!p,ia=a._adform&&a._adform.tagFrame,ja=!!ia,ka=function(a){for(var b=g.length,c,e=0;e<b;e++)g[e]&&(c=a.mraid||c),a=a.parent;return c}(a),P=!!ka,Q=k.sendBeacon&&!P,la=!(!a.XMLHttpRequest&&!Q||!a.FormData)&&!a.XDomainRequest,oa=function(){for(var b=a,d=m,c=g,e=1,f=c.length;e<f;e++)c[e]&&(b=d),d=d.parent;return b}();if("android"==ga||"ios"==ga)for(var ma in w)if(/^adObject.+/i.test(ma)){O=w[ma].inscreen;N=!!O;break}return{result:[u,x,p,S,G,B,A,V,C,H,I,q,r,J,K,W,L,D,
X,n,v,b,Y,Z,aa,ba,y,ca,!1,da,ea,z,M,l,e,fa,N,ha,ja,P,Q,la],exports:{nop:function(){},access:g,frame:u,accParent:x,accTop:p,isolate:S,flashVersion:E,hidden:T,hasHidden:G,isIE:B,ieVersion:U,addEvent:A,isMac:V,isApple:C,isIPad:H,isIPhone:I,isIOS:q,isIOSF:r,isGoogle:J,isAndroid:K,isTouch:W,isChrome:L,chromeVersion:F,isFirefox:D,isOpera:X,isOperaWebkit:n,isSafari:v,isIEMobile:b,isSafari5OrLess:Y,screenX:Z,outerWidth:aa,mozInnerScreenX:ba,msZF:y,ieDomEvents:ca,reqAni:na,isRad:!1,isIOSWebView:da,intersectionAPI:ea,
hasSrcDoc:z,isIOSOrAndroid:M,isOMID:l,hasFocus:e,IEVisibility:fa,isWisp:N,wisp:O,RAFVisibility:ha,asyncFrame:ia,isAsyncFrame:ja,mraid:ka,isMraid:P,hasBeacon:Q,usePOST:la,topAcc:oa}}}var x={$hash:function(){if(!m){for(var f=F(),t=f.result,f=f.exports,h=[],c=0,a=t.length,e=0,a=a+(6-a%6)%6;c<a;c++)e=e<<1|!!t[c],5==c%6&&(h.push("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.-".charAt(e)),e=0);for(c in f)x[c]=f[c];m=h.join("")}return m}},m;try{if(!Function("return ("+E+")(1)===1")())throw"Incorrect eval result";
}catch(f){R.log("function_constructor",f)}return x});
a(g,[c,b],function(n,d){var g=n.window,q=g.document,x=g.setTimeout;d.$hash();return function(a){var c,b,f,l,h,k,y=new Date;b=a.type;var r=a.placeId,z=/\.js(\?|$)/i,A=/\.swf(\?|$)/i,m=d.isIE,t=d.flashVersion,p=m&&10>d.ieVersion,m=!m&&21>t;c="standard"==a.type&&"flash"==a.subtype;var B=d.isSafari&&6.1<=d.safariVersion&&c,C=a.fVer||a.ADFVer||a.version,D=a.ADFPoliteSrc,u=a.sources||a.videoSources,v=["src","ADFFlash","ADFInitFlash","bsrc","ADFBuckup"];b=4==a.behavior?"Slider":b.charAt(0).toUpperCase()+
b.slice(1);c=["AdConstructor","types/"+b];if("Standard"==b){for(b=0;b<v.length;b++)(f=a[v[b]])&&(f.match(A)?l=f:f.match(z)?h=f:k=f);k&&p&&(h=0);k&&p&&(u=0);if(C>t||(k||h)&&(m||B))l=0;l?c.push("contents/FlashTag"):h?c.push("contents/HTML"):u&&c.push("contents/VideoTag");(!l&&!h&&k||D)&&c.push("contents/ImageTag")}n.require(c,function w(b,c){var e,d=b.cbuild;e="function"!==typeof c&&c;r?(e=q.getElementById(r)||e)?(a.placement=e.nextSibling||e.previousSibling,e&&e.parentNode.removeChild(e),d(a)):1E4>
new Date-y?x(function(){p&&(g.inDapMgrIf||g.inDapIF||g.inFIF)?w(b,q.body.firstChild):w(b)},0):n.rethrow("Failed to find placement","noplacement"):d(a)})}});
a(Q,[c,j],function(f,g){function e(a){return h(a).random()}function h(a){var e={random:k,int32:function(){var b,a,e=[0,2567483615];if(624<=c)for(a=c=0;624>a;a++)b=d[a]&2147483648|d[(a+1)%624]&2147483647,d[a]=d[(a+397)%624]^b>>>1^e[b&1];b=d[c++];b^=b>>>11;b^=b<<7&2636928640;b^=b<<15&4022730752;return(b^b>>>18)>>>0}},d=[],c;a||(a=Math.round(1E5*((new Date).getTime()+Math.random())));d[0]=a>>>0;for(c=1;a=c-1,624>c;c++)a=d[a]^d[a]>>>30,d[c]=(1812433253*((a&4294901760)>>>16)<<16)+1812433253*
(a&65535)+c,d[c]>>>=0;return e}function k(){return Math.floor(this.int32()/65535)}g.random=f.deprecate(e,"Adform.random is deprecated. Use h/random instead.");return e});
a(O,[c,j],function(e,a){function l(a,c){var f=c?9==c.nodeType?c:c.document:m;0<=a.indexOf('"')&&e.log("xss_detected",a);f.write('<script type="text/javascript" src="'+a+'">\x3c/script>')}function n(e){for(var c=a._prepareBannerDataCB,f={},d="ADFVideoCDN ADFDomainCDN ADFDomain VideoCDN ADFVideoCDNList ADFcmpgnID ADFmembID ADFtagID ADFafbanID ADFBanVer ADFBanVerBak ADFbanID ADFbanPlacID ADFUnloadID ADFClientSiteId ADFGeoData ADFGroupId ADFTemplateVersion ADFTemplateId ADF_ClickEvent".split(" "),
g=d.length-1;0<=g;g--)d[g]in h&&(f[d[g]]=h[d[g]]);var k=a.RMBData={clicktags:""};a._prepareBannerDataCB=function(){for(var b=d.length-1;0<=b;b--)d[b]in f&&(h[d[b]]=f[d[b]]);a.prepareBannerData(e);for(b in k)a.RMBData[b]="clicktags"!=b?k[b]:a.RMBData[b]+k[b];c&&c()};c||l(a.scriptBase+"bootstrap/Adform.BannerData.js?v="+a.cache)}var h=e.window,m=h.document;a.host&&(ADFDynamicDomain=a.host+"/banners/");a.shost&&(ADFTemplateDomain=a.shost+"/banners/");a.ENV={akamaiHost:("https:"==m.location.protocol?
"https://":"http://")+"adformvod-vh.akamaihd.net/i/Banners"};a.Log=a.Log||{sendMessage:e.log};a.loadResource=a.loadResource||l;a.prepareBannerData=a.prepareBannerData||n;return{loadResource:a.loadResource,prepareBannerData:a.prepareBannerData}});
a(P,function(){function f(a){a=a||"";var b=a.split(";oobclicktrack=");b.shift();b.length&&(this.tracks=b);a=a.split("?");this._base=a.shift();this._parts=a.join("?").split(";");this.append=[]}function g(a,b,c){var d=a.length;b+="=";var e,f=b.length;for(c||(b=b.toLowerCase());d--&&(e=a[d].slice(0,f),c||(e=e.toLowerCase()),e!==b););return d}var h=Object.prototype.hasOwnProperty,e=f.prototype;e.copy=function(){var a,b=new f;for(a in this)h.call(this,a)&&(b[a]=this[a]&&this[a].slice?this[a].slice(0):
this[a]);return b};e.get=function(a,b){var c=this._parts,d=g(c,a,b);if(~d)return c[d].slice(a.length+1)};e.set=function(a,b,c){var d=this._parts;c=g(d,a,c);0>c?d.push(a+"="+b):d[c]=d[c].slice(0,a.length+1)+b;return this};e.unset=function(a,b){var c=this._parts,d=g(c,a,b);~d&&c.splice(d,1);return this};e.toString=function(){return this._base+"?"+this._parts.join(";")+this.append.join("")};return f});
a(R,[c,b,O],function(n,c,k){var f=n.window,a=f.document,p=k.loadResource,q=c.isIE&&10>c.ieVersion;return function(c,g){function k(b){b||n.log("dv_not_blocked",g.BN,1,"info")}function r(b){var d=a.createElement("div");d.innerHTML=b;return d.firstChild}function t(b){var d=a.createElement("script");d.src=b;return d}function l(b,a){b.appendChild(a)}var h=a.body,e="_adform_dv_"+ +new Date+"_"+(Math.random()+"").slice(2),m='<script type="text/adtag"><script>'+e+"();</scr+ipt>\x3c/script>";
q&&(m+='<script type="text/passback"><script>'+e+'("P");</scr+ipt>\x3c/script>');f.replaceDocumentWrite&&a.writeln===a.write&&h?(l(h,r(m)),l(h,t(c)),l(h,r("<script>\x3c/script>"))):(a.write(m),p(c),q||a.write("<script>"+e+'("F");\x3c/script>'));f[e]=function(a){f[e]=k;a&&g.set("bsdata",g.BSDATA);p(g.toString())}}});
a(S,[c,b],function(k,l){function b(a,c){for(var d=[],e,f,b,g=0;g<a.length;g++)if(e=a[g])for(var h=0;h<c.length;h++)f=c[h],((b=e[f])||0==b)&&d.push(b);return d}return function(){if(l.accTop){var a=k.window.top,c=a.document,d=c.documentElement,e=c.body,c=b([a,d,e],["pageYOffset","scrollTop"])[0],f=Math.max.apply(null,b([d,e],["scrollHeight","offsetHeight","clientHeight"])),a=b([a,d,e],["innerHeight","clientHeight"])[0];return f==a&&0==c?1:0}}});
a(e,function(){function m(a,b){(b=b||[]).push(a);for(var d=0;d<a.frames.length;d++)m(a.frames[d],b);return b}function t(a,b,d){a.addEventListener?a.addEventListener(b,d,!1):a.attachEvent&&a.attachEvent("on"+b,d)}function u(a,b,d){a.removeEventListener?a.removeEventListener(b,d,!1):a.detachEvent&&a.detachEvent("on"+b,d)}function n(){if(c)return{cmpFrame:c,isCrossDomain:g};for(var a=window;a;){if(f(function(){return a.frames.__tcfapiLocator})){c=a;break}if(f(function(){return a.frames.__cmpLocator})){c=
a;break}if(a===v)break;a=a.parent}c&&(g=!f(function(){return!!c.document.getElementById}));return{cmpFrame:c,isCrossDomain:g}}function k(){if(g&&c&&c.postMessage){var a=window.__cmp,b=window.__tcfapi;u(window,"message",p);t(window,"message",p);c.postMessage({__cmpCall:{command:"getConsentData",callId:q++}},"*");c.postMessage({__tcfapiCall:{command:"getTCData",callId:q++}},"*")}else c?(a=c.__cmp,b=c.__tcfapi):(a=window.__cmp,b=window.__tcfapi);a&&f(function(){return a("getConsentData",null,l)});b&&
f(function(){return b("getTCData",null,l)})}function p(a){var b=a.data;"string"===typeof b&&(b=f(function(){return window.JSON.parse(b)}));b&&(b=(b.__cmpReturn||b.__tcfapiReturn||{}).returnValue);b&&null!=b.gdprApplies&&(a=b,l({gdprApplies:a.gdprApplies,consentData:a.consentData,tcString:a.tcString}))}function l(a){a=void 0===a?{}:a;var b=h("Adform",{}),d=a.gdprApplies;b.gdpr="1"==d?1:"0"==d?0:void 0;b.gdpr_consent=a.tcString||a.consentData;a=b.gdpr;for(b=b.gdpr_consent;e.length;)e.shift()({gdpr:a,
gdpr_consent:b})}function f(a){try{return a()}catch(b){}}var h=function(a,b){var d,c,e=m(window.top);for(d=e.length;d--;)try{if((c=e[d])&&(c=c[a])&&(c=c.shared))return c}catch(f){}return window[a].shared=b},v=window.top,w=window.setTimeout,c,g,q=1,e=[],r=window.Adform=window.Adform||{};r.getConsent=function(){k();var a=h("Adform",{});return{gdpr:a.gdpr,gdpr_consent:a.gdpr_consent}};r.waitForConsent=function(a,b){b=void 0===b?1E4:b;n();c||window.__cmp||window.__tcfapi?(e.push(a),k(),w(function(){var b=
e.length;if(e.indexOf)b=e.indexOf(a);else for(;b--&&e[b]!==a;);if(-1<b){var c=h("Adform",{}),f=c.gdpr,c=c.gdpr_consent;e.splice(b,1)[0]({gdpr:f,gdpr_consent:c})}},b)):a(null,"CMP not found.")};n();h("Adform",{});k();return window.Adform});
a(J,[c,b,j,g,Q,O,P,R,S,e],function(z,w,f,V,A,e,W,M,X,Y){function x(){var a,b;if(y)return y;this.banners={};this.compoundBanners={};try{k.body||k.write("<html><body></body></html>")}catch(d){}a=n.browserLanguage||n.language||0;b=this.getWin();this.settings=[escape(n.systemLanguage||a),escape(a),v?v.width+"X"+v.height:0,w.flashVersion,50*Math.round(b.w/50),50*Math.round(b.h/50),v?v.colorDepth:0,8,
3,7,this.hasIframeSanbox()].join("|")}function N(a){function b(b){e(["3rdparty/vendor/Adform"],function(c){c(a,b)})}var d=a.placeId="+ADFP"+a.adfxid,c=a.innerTagId,f=["types/ThirdParty"],e=z.require;k.write('<i id="'+d+'" style="display:none"></i>');c&&(_adform.push([c+".on.setup",b]),f.push("3rdparty/vendor/Adform"));e(f,function(b){b(a)})}function O(a){var b,d,c;if(a=a||f.BannerList&&f.BannerList.shift()||f.RMBData)b=a.type,d=a.behavior,c=a.adfxid||a.ADFid,a._beforeScript=f._beforeScript,f._beforeScript=
!1,{standard:1,expanding:1,singleExpanding:1}[b]&&![0,0,0,1,1][d]&&(a.placeId="+ADFP"+c,b=y.banners[c],k.write('<div id="'+a.placeId+'"'+(b.singleTag?"":' style="width:'+b.width+"px;height:"+b.height+'px;"')+'></div><i style="display:none"></i>')),V(a)}function C(a,b,d){var c=(d=d||k).createElement("div");c.innerHTML='<iframe src="'+a+'" allowtransparency="true" webkitallowfullscreen mozallowfullscreen allowfullscreen marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no" width="1" height="1" style="'+
b+'"></iframe>';d.body.appendChild(c.removeChild(c.firstChild))}function P(a){var b,d,c,e=/\/adfscript/,B=f.ADFIframe&&{src:g.location.href.replace(/cpjs=2/,"cpjs=0")};if(!B)for(b=k.getElementsByTagName("script"),d=b.length;d--&&!B;)(c=b[d]).src&&c.src.match(e)&&-1<c.src.indexOf(a)&&(B=c);return B||{}}function Z(a){var b,d;d=w.asyncFrame;var c=a;if("undefined"!=typeof a.URL){try{b=g.top.location.href.split("#")[0]}catch(f){b=d||g,b=(d=(d=b.location.ancestorOrigins)&&d[d.length-1])||b.document.referrer}b=
b?D(b):a.CREFURL;c=new W(a.URL);c.append.push("&CREFURL="+b);c.CREFURL=b;c.STUBFILE=a.STUBFILE;c.BSURL=a.BSURL;c.BSDATA=a.BSDATA;c.BN=a.BN;c.READ_CONSENT=a.READ_CONSENT;c.ROTSEQ=a.ROTSEQ}return c}function F(a,b){try{if(a){(b=b||[]).push(a);for(var d=0;d<a.frames.length;d++)F(a.frames[d],b);return b}}catch(c){}}function Q(a){return A(a+this.id)}function R(a){try{return a.Adform&&a.Adform.ADFUtilInstance}catch(b){}}function G(){return(new Date).getTime()}function S(a){try{return aa(a)}catch(b){return a}}
var y,m,H,I,r,J,g=z.window,ba=g.top,k=g.document,n=g.navigator,v=g.screen,ca=g.setTimeout,K=g.Image,da=Object.prototype.hasOwnProperty,E=e.loadResource,D=g.encodeURIComponent,aa=g.decodeURIComponent,T=f.cache,L=[];e=x.prototype;var U={webkitVisibilityState:"webkitvisibilitychange",mozVisibilityState:"mozvisibilitychange",msVisibilityState:"msvisibilitychange",visibilityState:"visibilitychange"};_adform=g._adform||[];if(f.ADFBannerUtils)return f.ADFBannerUtils;for(r in U)r in k&&(H=r,I=U[r]);e.getCompoundBannerInfo=
function(a){return this.compoundBanners["c"+a]||null};e.createBanner=function(a){function b(a){var b=a.url;"stubFileExists"in p||(a.helper&&ca(function(){z.log("StubFileError","Cref: "+t+" > Adfserve: "+l+" > bn: "+u,0,"error")},100),(p.stubFileExists=a.exists)?(b=S(b),C(f.scriptBase+"iframe/recache.html?bv="+T,"position:absolute;width:10px;height:10px;left:-9999px;top:-9999px"),C(b+"#"+T+"#"+P(u).src,"position:absolute;top:0;left:0;width:100%;height:100%",w.asyncFrame)):((d=f.RMB)&&(d=d.AdConstructor)&&
(d=d.cbuild)||(f.RMB=f.RMB||{},f.RMB.AdConstructor={build:O},f.thirdPartyCB=N),r?M(r,h):E(l)))}var d,c,e,g,l,m,q=this,n=q.getTagID(),p=q.addNewBanner(n,"undefined"==typeof f.ADFIframe?0:1),h=p.params=Z(a,q);g=h.get("compoundSeqNo");var u=h.BN,v=q.getCompoundBannerInfo(u),x=q.getPropByBn("smid",u),y=h.ROTSEQ,t=h.CREFURL;a=h.STUBFILE;var r=h.BSURL,A=h.READ_CONSENT;h.tracks&&(p.OOBClickTracks=h.tracks);h.get("singleTag")&&(p.singleTag=!0,g=g||1,h.set("compoundSeqNo",g));p.compoundSeqNo=g;"prerender"==
k[H]&&(h.set("hid",2),p.prerender=!0,k.addEventListener(I,function(){"prerender"!=k[H]&&p.prerender&&(k.removeEventListener(I,arguments.callee,!1),q.registerImpression(p))},!1));g&&(g=q.getRotSeed(),c=g.gen(u),g.compound[u]?e=g.compound[u]:y&&(g.compound[u]=y));h.set("js",1);h.set("adfxid",n);h.set(Math.floor(11E3*Math.random())+";set",q.settings+"|"+X());c&&h.set("rotseed",c);e&&h.set("rotseq",D(e));v&&h.set("rotseqno",v.replace("r",""));x&&h.set("smid",x);f.CDNHost&&h.set("cdnhost",D(f.CDNHost));
A&&(c=Y.getConsent(),h.set("gdpr",void 0==c.gdpr?"":c.gdpr),h.set("gdpr_consent",void 0==c.gdpr_consent?"":c.gdpr_consent));h.set("fd",w.accTop?""===ba.document.title?"2|2":"0|2":"0|0");l=h.toString();t&&a&&!f.ADF_STUB&&(t=S(t).replace(/(:\/\/[^\/]+).*/,"$1"),m=a.HOST?t.split("/")[2]===a.HOST&&q.needStubFile(t):q.needStubFile(t));m?(f.stubFile=b,m=f.shost+"/adfstub/?url="+D(t+a.PATH),E(m),E(f.scriptBase+"extra/StubHelper.js?bv="+f.cache)):(f.ADF_STUB&&z.log("adfstub",u+" "+t,1,"info"),(d=f.RMB)&&
(d=d.AdConstructor)&&(d=d.cbuild)||(f.RMB=f.RMB||{},f.RMB.AdConstructor={build:O},f.thirdPartyCB=N),r?M(r,h):E(l));return p};e.addNewBanner=function(a,b){return this.banners[a]={id:a,type:b,adfserveLoadTime:G()}};e.copyBanner=function(a,b){var d,c=this.banners[a];if(c=c&&c.params||null){c=c.copy();for(d in b)da.call(b,d)&&c.set(d,b[d]);c=this.createBanner(c)}return c};e.wipeOutBanner=function(a){var b=this.banners[a];b&&(m&&(m.id=A(),m.compound&&delete m.compound[b.bn]),delete this.compoundBanners["c"+
b.bn],delete this.banners[a])};e.addBannerAttribute=function(a,b,d){(a=this.banners[a])&&(a[b]=d)};e.getTagID=function(){var a=this.getRotSeed();a.xId||(a.xId=0);return++a.xId+"x"};e.getRotSeed=function(){var a,b,d,c,e;if(!m&&!J){J=!0;try{for(a=F(g.top),b=0,d=a.length;b<d;b++)if(c=a[b],c!=g&&(e=R(c))&&e.getRotSeed){m=e.getRotSeed();break}}catch(f){}m?m.gen=Q:m={compound:{},id:A(),gen:Q}}J=!1;return m};e.getFlashVersion=z.deprecate(function(){return w.flashVersion},"Utils_getFlash");e.getWin=function(){var a=
k.documentElement,b=k.body;return{w:g.innerWidth||a&&a.clientWidth||b&&b.clientWidth,h:g.innerHeight||a&&a.clientHeight||b&&b.clientHeight}};e.getSettings=function(){return this.settings};e.firePixel=function(a){("undefined"==typeof K?k.createElement("img"):new K).src=a};e.fireTargAdPixel=function(a){var b=this.TargAd||{};b[a]||((this.TargAd=b)[a]=!0,a=a.replace("{gmtr}",Math.floor(9999999999*Math.random())).replace("{gmttzd}",(new Date).getTimezoneOffset()),this.firePixel(a))};e.registerImpression=
function(a){var b,d;a&&a.prerender&&(b=a.params.copy(),b.set("hid",1),a.rotseqno&&b.set("rotseqno",a.rotseqno),d=k.createElement("script"),d.src=b.toString(),d.type="text/javascript",k.body.appendChild(d),delete a.prerender)};e.addCompoundBannerInfo=function(a,b){this.compoundBanners["c"+a]="r"+b};e.setBannerRegisteredStatus=function(a){var b,d,c=this.banners[a];if(c){var e=G(),g=e-c.adfserveLoadTime,l=parseInt(c.serverTime,10),k=f.ADFEventsInstance;c._host=f.host;c.adfserveLoadTime=g;l&&(l+=Math.round(.5*
g),c.serverTime=l,c.timeDiff=l-e);c.registered=1;this.sendLoadMetrics(a);if(c.singleTag&&1==c.compoundSeqNo)for(b=2,d=c.syncMembersCount;b<=d;b++)this.copyBanner(a,{compoundSeqNo:b,compoundImpr:0});try{for(k&&k.register(c),b=0,d=L.length;b<d;b++)L[b].call(this)}catch(m){}}};e.onBannerRegisteredStatus=function(a){L.push(a)};e.hasIframeSanbox=function(){var a=this._sandbox;if("number"!=typeof a){a=1;try{g.top.document.getElementById,a=0}catch(b){}this._sandbox=a}return a};e.getPropByBn=function(a,b){var d,
c,e=this.banners;for(d in e)if(c=e[d],c.bn==b&&a in c)return c[a]};e.now=G;e.needStubFile=function(a){var b=g.$sf,d=g.parent,c=this._stub,e=w.asyncFrame,f=/^https?:/,l=g.location.protocol;if(null==c){c=!(g==d||g.inDapMgrIf||g.inDapIF||g.inFIF||b&&b.ext);!c&&e&&(c=!0,d=e.parent);if(c)try{d.document.getElementById,c=!1}catch(k){}c&&(l=l.match(f)?l:null,w.accParent&&!l&&(l=d.location.protocol,l=l.match(f)?l:null),c=a.split("/")[0]===l);this._stub=c}return c};e.getAdfscript=P;e.getUnloadId=function(a){try{for(var b,
d,c,e,f=F(g.top),k=f.length;k--;)for(c in b=(d=R(f[k]))&&d.banners,b)if(e=b[c],e.bn==a&&1==e.compoundSeqNo)return e.unloadID}catch(m){}};e.sendLoadMetrics=function(a){a=this.banners[a];var b=g.ADFGeoData,d=(f.shost||"").split("/")[0]+"//"+"s2.adform.net/stoat/620/s2.adform.net/load".replace("/load","")+"/bootstrap.js",c=g.performance,d=(d=c&&c.getEntriesByName&&c.getEntriesByName(d))&&d[0]&&d[0].duration;!a.metricsSent&&"string"==typeof b&&.1>Math.random()&&(b=b.split(";"),3==b.length&&((new K).src=f.host+"/jsmetrics/?adfserve="+a.adfserveLoadTime+
(d?"&asset="+parseInt(d,10):"")+"&sid="+b[2]+"&rid="+b[1]+"&cid="+b[0]));a.metricsSent=!0};e.loadFrame=C;e.loadTrackingIframes=function(a){var b=this.getRotSeed();if(a&&a.length&&!b.framesLoaded)for(b.framesLoaded=!0,b=a.length;b--;)C(a[b],"display:none")};e.ADFCreateObjectCallback=function(a,b){return function(){b.apply(a,arguments)}};e.eventRegister=function(){};e.getPosition=function(a){for(var b={x:0,y:0};a;)b.x+=a.offsetLeft,b.y+=a.offsetTop,a=a.offsetParent;return b};e.getScrollXY=function(){var a=
k.body,b=k.documentElement,d={x:0,y:0};"number"==typeof g.pageYOffset?(d.y=g.pageYOffset,d.x=g.pageXOffset):a&&(a.scrollLeft||a.scrollTop)?(d.y=a.scrollTop,d.x=a.scrollLeft):b&&(b.scrollLeft||b.scrollTop)&&(d.y=b.scrollTop,d.x=b.scrollLeft);return d};e.getBrowser=function(){try{var a=n.userAgent;return~n.appVersion.indexOf("MSIE")&&0>a.indexOf("Opera")?"MSIE":~a.indexOf("Safari")?"Safari":~a.indexOf("Opera")?"Opera":~a.indexOf("Netscape")?~n.product.indexOf("Gecko")&&(~n.vendor.indexOf("Firefox")||
~a.indexOf("Firefox"))?"Firefox":"Netscape":void 0}catch(b){}};f.ADFUtilInstance=y=new x;return f.ADFBannerUtils=x.getInstance=x});
a(L,[c,j,J],function(b,e,c){var l=Object.prototype.hasOwnProperty,m=b.window,n=m.document;b={Initialized:!1,InitTime:(new Date).getTime(),Host:e.host||("https:"==n.location.protocol?"https://":"http://")+"track.adform.net",callbacks:[],sendEvent:function(p,f,b,c,h){var d,g,a,k;g=Math.round(((new Date).getTime()-this.InitTime)/1E3);a=q.banners[p];k=e.adRegister&&e.adRegister[p];try{this.notifyAboutEvent.apply(this,arguments)}catch(l){}if(!a&&k)d=k.sendEvent(f,b,c,h);
else if(a&&a.isEventsEnabled){d=a.bn;!a._imprID&&1<a.compoundSeqNo&&(a._imprID=q.getUnloadId(d)||a.unloadID);g=["bn",d,"event",f,"time",(0>g?0:3600<g?3600:g)+"","baid",a.ban,"innerbanner",a.innerban,"asid",b,"name",c,"imprid",a._imprID||a.unloadID,"icid",a.cookieID,"eData",a.eData,"adxvars",a.adxvars,"rtbdata",a.rtbdata,"rtbwp",a.rtbwp,"rnd",Math.floor(1E9*Math.random())];a=0;for(d=[];a<g.length;a+=2)(k=g[a+1])&&d.push(g[a]+"="+encodeURIComponent(k));d=this.Host+"/Serving/Event/?"+d.join("&")+(h||
"");(m.Image?new m.Image(1,1):n.createElement("img")).src=d}return d},Initialize:b.deprecate(function(){this.Initialized=!0},"initEvents",1),registerCallback:function(b,f){"function"==typeof b&&this.callbacks.push([b,f])},unregisterCallback:function(b){var f=this.callbacks,c=f.length;if("function"==typeof b)for(;c--;)f[c][0]==b&&f.splice(c,1)},notifyAboutEvent:function(){for(var b=this.callbacks.slice(),c=0,e=b.length;c<e;c++)b[c][0].apply(b[c][1]||this,arguments)}};var q=c();if(c=e.Events){for(var h in b)l.call(b,
h)&&!l.call(c,h)&&(c[h]=b[h]);c.sendEvent=b.sendEvent}else c=e.Events=b;e.ADFEvents2||(e.ADFEvents2=c);return b});
a(M,[c,j],function(g,b){function d(c){try{var e=c.URL,d=c.BN,h,a,n,k;c=/\/adfscript/;var l=b.ADFIframe&&{src:r.location.href.replace(/cpjs=2/,"cpjs=0")};if(!l)for(a=m.getElementsByTagName("script"),n=a.length;n--&&!l;)(k=a[n]).src&&k.src.match(c)&&-1<k.src.indexOf(d)&&(l=k);h=l||m.currentScript||{};var f=m.createElement("div");a=h;var p,t,q,u,e=e.split(";");e[0]+=";srctype=6";for(e=e.join(";");a;)p="BODY"==a.nodeName,t="HEAD"==a.nodeName,a=!(p||t)&&a.parentNode;p?(q=h.parentNode,u=
h):q=m.body;f.innerHTML='<a href="'+b.host+"/C/?bn="+d+';C=0"><img src="'+e+'"></a>';q.insertBefore(f.firstChild,u||null);g.log("fallback",d)}catch(v){g.rethrow(v,"fallback_error")}}var f,r=g.window,m=r.document;g.require(["$ignore"],function(){var c=b.ADFBannerParams;f||(b.ADFUtilInstance||(b.ADFUtilInstance={}),b.ADFBanner||(b.ADFBanner=d),d(c&&c.length?c.shift():b.ADFBannerData))});return{cancel:function(){f=!0},write:d}});
a(z,[j],function(l){function g(){}function h(b){b?this._events&&this._events[b]&&delete this._events[b]:delete this._events;return this}function k(b){var a=this._events;a||(this._events=a={});return a[b]||(a[b]=[])}var m=Array.prototype.slice,f=g.prototype;l.RMB.EventEmitter=g;f.emit=function(b){var a,c,d,e=this._events;if(e&&(e=e[b])&&(c=e.length))for(d=m.call(arguments,1),e=e.slice(),a=0;a<c;a++)e[a].apply(this,d);return this};f.on=function(b,a){this.emit("newListener",b,a);k.call(this,
b).push(a);return this};f.once=function(b,a){var c=function(){return a.apply(this.off(b,c),arguments)};c._oncep=a;return this.on(b,c)};f.off=function(b,a){var c,d=(c=this._events)&&c[b];if(d){for(c=d.length;c--;)d[c]!=a&&d[c]._oncep!=a||d.splice(c,1);d.length||h.call(this,b);this.emit("removeListener",b,a)}return this};f.clear=h;f.list=k;return g});
a(B,[c,J],function(t,x){function m(g,l){for(var a in l)l.hasOwnProperty(a)&&("object"==typeof l[a]?("object"!=typeof g[a]&&(g[a]={}),m(g[a],l[a])):g[a]=l[a])}var q=t.window,y=q.parent,r={useClose:"expImage.useClose",overlay:"overlay",wallpaper:"options.wallpaper",x:"options.x",y:"options.y",hidden:"options.hidden",position:"options.position",adNotice:"options._adNotice",fixedBounding:"options.fixedBounding",resizeInFIF:"options.iabResize",panel:"panel",responsive:"options.responsive",
testPlace:"options.testPlace"};return function(g,l){var a,u,h,f,n,c,d,b,v,k;d=g.options;b=d.bn;c=x();var e;try{e=((d.iab?y:q)._adform||[]).slice(0)}catch(w){e=[]}var z=/(?:(\d+x|\d+#\d+|#[-_0-9a-z]+|\d+))?\.?(.*)/i,p={};d.iab&&e.push.apply(e,q._adform||[]);c&&c.getPropByBn&&(c=c.getPropByBn("multiPanel",b))&&e.push.apply(e,c);if(c=(d.userParams||{})._adform)try{if((c=Function("return ("+c+")")())&&"object"==typeof c)(e=e||[]).push([d.xId,c]);else throw Error("_adform from userParams should be an object");
}catch(w){t.rethrow(w,"user_params")}if("[object Array]"==Object.prototype.toString.call(e)&&e.length){d=l||["",b,"#"+d.seqNo,b+"#"+d.seqNo,d.xId];b=0;c=d.length;for(v=e.length;b<c;b++)p[d[b]]={};for(b=0;b<v;b++)if(a=e[b][0].match(z),u=p[a[1]||""]){h=e[b][1];if(a[2]){a=a[2].split(".");for(n=f={};1<a.length;)f=f[a.shift()]={};f[a[0]]=h;h=n}if(a=h.on)for(k in a){if("function"==typeof a[k])g.events.on(k,a[k])}else if(h.init)g.events.on("init",h.init);a={};for(f in h)r[f]&&(a[f]=h[f]);m(u,a)}k=p[d[0]];
for(b=1;b<c;b++)m(k,p[d[b]]);for(b in r)if(b in k){a=r[b].split(".");for(n=f={};1<a.length;)f=f[a.shift()]={};f[a[0]]=k[b];m(g,n)}}}});
a(x,[c,b],function(d,f){return function(a,b){var c=d.window,g=c.navigator,e=c.Image;try{f.hasBeacon?g.sendBeacon(a,""):((new e).src=a,b&&c!=b&&((new b.Image).src=a))}catch(h){(new e).src=a,d.log("beacon_failure",h+"_"+a,.1,"info")}}});
a(N,[c,j,J,z,B,x],function(v,q,z,I,J,K){function t(c){for(var d=0,k=c.length;d<k;d++){var a=c[d],l=void 0,p=void 0,e,h,f,t=q.scriptBase,u=q.cache,b,g,r;f=void 0;h=a.xId;var A=a.externalScripts,B=a.trackingPixelUrls;b=a.banner;var w=b.backup,m=b.type,H=b.innerTagId;g=b.clickUrls;var z=a.visibility.testMode,G=a.trackingIframeUrls;r=a.geoLocation;var n={};e=a.csImpressionUrl;var C=x.banners[h];A&&(l=A.before,p=A.after);l&&(D(l),q._beforeScript=
!0);x.loadTrackingIframes(G);C&&(E(L,a,C),C.isDSPTag="dsp"===a.impressionType,x.setBannerRegisteredStatus(h));if("thirdparty"===m.type){b={bn:b.tagId,xId:h,bannerId:b.id};g={adfxid:h,options:b};H&&(g.innerTagId=H);r=g.events=new I;a=a.banner.script;J(g,[b.bn]);q.thirdPartyCB&&q.thirdPartyCB(g);try{r.emit("setup",g)}catch(F){v.rethrow(F,"setup")}try{(f=b.wrapper)?y.write(M(f,a)):y.write(a)}catch(F){v.rethrow(F,"thirdPartyWrite")}e&&K(e)}else if("standard"!=m.type||"image"!=m.subType&&"flash"!=m.subType&&
"html"!=m.subType)v.log("rollback",b.tagId+" banner not rendered",1,"error");else{f=b.properties;f={type:m.type,subtype:m.subType,landingPageTarget:f.landingTarget,ADFFlash:b.asset&&b.asset.url||b.url,ADFBuckupClickURL:w&&w.clickUrl||a.clickUrl,width:b.size.width,height:b.size.height,ADFid:h,ADFban:b.tagId,bannerAlign:f.align,clicktags:n,flashvars:n,defaultClickTAG:g[0]&&g[0].name,css:t+"assets/css/Adform.RMB.css?bv="+u,quality:f.quality,wmode:f.wMode,fVer:f.flashVersion};w&&(f.ADFBuckup=w.url);e=
0;for(h=g.length;e<h;e++)n[g[e].name]=encodeURIComponent(g[e].url);E(N,a,n);n.domain=encodeURIComponent(a.staticContentUrl);n.bn=b.tagId;n.geo=[r.city.id,r.region.id,r.country.id].join(";");q.RMB.AdConstructor.build(f)}if(B)for(e=0,h=B.length;e<h;e++)x.fireTargAdPixel(B[e]);p&&D(p);z&&D([t+"unload/Adform.Inscreen.js?"+u])}}function u(){G.apply(this,arguments);t(arguments)}function D(c){for(var d=0;d<c.length;d++)y.write('<script src="'+c[d]+'">\x3c/script>')}function E(c,d,k){var a,l;for(a in c)l=
c[a],"string"===typeof l?null!=d[a]&&(k[l]=d[a]):d[a]&&E(l,d[a],k)}function M(c,d){var k=y.createElement("div");k.innerHTML=c;var a=k.firstChild;a.innerHTML=d;return a.firstChild&&1==a.firstChild.nodeType?k.innerHTML:d}var p=v.window,y=p.document,G=Array.prototype.push,x=z(),L={visitor:{cookieId:"cookieID",isMobile:"isMobile",gdpr:"gdpr",gdpr_consent:"gdpr_consent",us_privacy:"us_privacy",isCcpaOptOut:"isCcpaOptOut"},csImpressionUrl:"csImpressionUrl",eData:"eData",uData:"uData",interactionId:"unloadID",
visibility:{sendUnload:"sendUnloadData",area:"visibilityArea",time:"visibilityTime"},serverTime:"serverTime",banner:{id:"ban",version:"bannerVersion",template:{dcoEngineId:"dcoEngineId"},size:{width:"width",height:"height"},rotationSeqenceNumber:"rotseqno",smId:"smid",tagId:"bn",campaignId:"pm",membershipId:"ms",bannerPlacementId:"bnpl",isEventEnabled:"isEventsEnabled"},isAdNoticeEnabled:"adNotice",publisher:{adxvars:"adxvars",publisherUnloadData:"publisherUnloadData",visibility:{area:"publisherVisibilityArea",
time:"publisherVisibilityTime"}},dsp:{inventorySourceId:"rtbInventorySourceId",requestId:"rtbReqId",rtbdata:"rtbdata",rtbwp:"rtbwp"},disableFlash:"disableFlash"},N={banner:{clientSiteId:"cid",template:{groupId:"gid",version:"tv",id:"tid"},version:"bv",campaignId:"ADFcmpgnID",membershipId:"ADFmembID",id:"ADFbanID",bannerPlacementId:"ADFbanPlacID",properties:{wMode:"wmode"},dynamicAdContent:"dynamicAdContent"},xId:"ADFid",interactionId:"unloadID",trackingSetupId:"trackingSetupId"};return function(){var c=
p.adfjsonbanners;c?(c.push=u,t(c)):(c=[],c.push=u,p.adfjsonbanners=c)}});
a(K,[c,j,L,M,J,N],function(g,a,c,f,h,k){function d(){var b=a.ADFBannerParams,e=b&&b.length?b.shift():a.ADFBannerData;if(e)try{h().createBanner(e)}catch(c){g.rethrow(c,"create_banner"),f.write(e)}b&&b.length&&d()}a.ADFBanner||(a.ADFBanner=d,a.ADFBanner());k();c.IE=9;f.cancel();return d});
a(f,function(){return"vCAv.IAAAAFAAA"});
})(_adfq.define,"Adform","$boot","$env","$main","h/random","bootstrap/Global","bootstrap/URL","bootstrap/dv","bootstrap/isAppView","consent-amd","bootstrap/Utils","bootstrap/Events","bootstrap/Fallback","common/EventEmitter","api/ARMA","h/beacon","bootstrap/adfjsonbanners","bootstrap/Banner","$ignore");